---
title: "HTML Presentations or: How I Learned to Stop Worrying and Love the Web"
subtitle: "enter text here"
author: 
  - .b[Matthew T. Warkentin] .blue[&commat;mattwrkntn]
institute: ".small[.blue-medium[Lunenfeld-Tanenbaum Research Institute]]"
date: 'October 21, 2020'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: 
      - css/xaringan-theme.css
      - css/style.css
    seal: false
    nature:
      titleSlideClass: ["bottom", "left"]
      slideNumberFormat: "%current%"
      highlightStyle: atom-one-light
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

name: title
class: left middle hide-count title-bg

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
source("xaringan-theme.R")
source("packages.R")
source("setup.R")$value
```

```{r title-slides, echo=FALSE, message = FALSE, warning = FALSE}
htmltools::withTags(
  div(
    class = "talk-meta",
    div(
      class = "talk-title",
      h1(rmarkdown::metadata$title),
      p(rmarkdown::metadata$subtitle)
    ),
    div(
      class = "talk-author",
      paste(rmarkdown::metadata$author, collapse = " <br> "),
      br(),
      span(paste(rmarkdown::metadata$institute, collapse = ", "))
    ),
    div(
      class = "talk-date",
      knitr::knit(text = rmarkdown::metadata$date, quiet = TRUE)
    )
  )
)
```
